load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "golib",
    srcs = [
        "fortune/fortune.go",
    ],
    importpath = "monorepo.local/backend/golib/fortune",
    visibility = ["//visibility:public"],
)
