load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "golib",
    srcs = ["fortune.go"],
    importpath = "example.com/backend/golib/fortune",
    visibility = ["//visibility:public"],
)

